import PptxGenJS from "pptxgenjs";
import { openai } from "../../../lib/openai";

// =========================
// SUPER SAFE CLEAN TEXT
// =========================

function cleanText(text: any) {
  if (!text) return "";

  return String(text)
    // remove unicode
    .replace(/[^\x20-\x7E]/g, " ")

    // remove dangerous chars
    .replace(/[<>&"'`]/g, "")

    // remove markdown
    .replace(/[#*_~\-]/g, "")

    // normalize spaces
    .replace(/\s+/g, " ")

    // limit length
    .slice(0, 150)

    .trim();
}

export async function POST(req: Request) {
  try {
    const body = await req.json();

    const topic = cleanText(body.topic || "Presentation");

    const totalSlides = Number(body.slides || 5);

    // =========================
    // AI GENERATE CONTENT
    // =========================

    let slides: any[] = [];

    try {
      const ai = await openai.chat.completions.create({
        model: "gpt-4.1-mini",

        messages: [
          {
            role: "system",
            content: `
Buat presentasi profesional.

ATURAN:
- Bahasa Indonesia
- Profesional
- Ringkas
- Maksimal 4 point
- Jangan emoji
- Jangan markdown

WAJIB JSON VALID SAJA

Format:
[
  {
    "title": "Judul Slide",
    "content": [
      "Point 1",
      "Point 2",
      "Point 3"
    ]
  }
]
`,
          },

          {
            role: "user",
            content: `
Buat ${totalSlides} slide tentang "${topic}"
`,
          },
        ],

        temperature: 0.7,
      });

      const raw = ai.choices[0].message.content || "[]";

      const parsed = JSON.parse(raw);

      if (Array.isArray(parsed)) {
        slides = parsed;
      }
    } catch (error) {
      console.error("AI ERROR:", error);

      slides = [
        {
          title: `Pendahuluan ${topic}`,
          content: [
            "Pengenalan topik",
            "Latar belakang",
            "Tujuan pembahasan",
          ],
        },
      ];
    }

    // =========================
    // SAFE SANITIZE
    // =========================

    slides = slides.map((slide: any) => ({
      title: cleanText(slide.title || "Slide"),

      content: Array.isArray(slide.content)
        ? slide.content.map((x: any) => cleanText(x))
        : ["Konten"],
    }));

    // =========================
    // INIT PPT
    // =========================

    const pptx = new PptxGenJS();

    pptx.layout = "LAYOUT_WIDE";

    pptx.author = "AI PPT Generator";
    pptx.company = "AI SaaS";
    pptx.subject = topic;
    pptx.title = topic;

    // =========================
    // COVER SLIDE
    // =========================

    const cover = pptx.addSlide();

    cover.background = {
      color: "0F172A",
    };

    cover.addText(topic, {
      x: 1,
      y: 2,
      w: 10,
      h: 1,
      fontSize: 30,
      bold: true,
      color: "FFFFFF",
    });

    cover.addText("Generated by AI PPT Generator", {
      x: 1,
      y: 3,
      w: 6,
      h: 0.5,
      fontSize: 16,
      color: "CBD5E1",
    });

    // =========================
    // CONTENT SLIDES
    // =========================

    slides.forEach((item: any, index: number) => {
      const slide = pptx.addSlide();

      slide.background = {
        color: "FFFFFF",
      };

      // TOP BAR
      slide.addShape(pptx.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.25,
        fill: {
          color: "2563EB",
        },
        line: {
          color: "2563EB",
        },
      });

      // TITLE
      slide.addText(item.title, {
        x: 1,
        y: 0.7,
        w: 9,
        h: 0.5,
        fontSize: 24,
        bold: true,
        color: "111111",
      });

      // CONTENT BOX
      slide.addShape(pptx.ShapeType.rect, {
        x: 0.8,
        y: 1.6,
        w: 6.2,
        h: 3.8,
        fill: {
          color: "F8FAFC",
        },
        line: {
          color: "E2E8F0",
        },
      });

      // SAFE TEXT (NO UNICODE BULLET)
      const bulletText = item.content
        .slice(0, 4)
        .map((x: string, i: number) => {
          return `${i + 1}. ${cleanText(x)}`;
        })
        .join("\n");

      // CONTENT
      slide.addText(String(bulletText), {
        x: 1.1,
        y: 2,
        w: 5.5,
        h: 3,
        fontSize: 18,
        color: "334155",
      });

      // VISUAL BOX
      slide.addShape(pptx.ShapeType.rect, {
        x: 7.5,
        y: 1.6,
        w: 4.8,
        h: 3.8,
        fill: {
          color: "DBEAFE",
        },
        line: {
          color: "93C5FD",
        },
      });

      slide.addText("AI VISUAL", {
        x: 8.7,
        y: 3.1,
        w: 2.5,
        h: 0.5,
        fontSize: 20,
        bold: true,
        color: "1D4ED8",
        align: "center",
      });

      // FOOTER
      slide.addText(`Slide ${index + 1}`, {
        x: 11.5,
        y: 7,
        w: 1,
        h: 0.3,
        fontSize: 10,
        color: "999999",
      });
    });

    // =========================
    // EXPORT PPT (STABLE)
    // =========================

    const buffer = await pptx.write({
      outputType: "base64",
    });

    const binary = Buffer.from(buffer as string, "base64");

    return new Response(binary, {
      status: 200,

      headers: {
        "Content-Type":
          "application/vnd.openxmlformats-officedocument.presentationml.presentation",

        "Content-Disposition":
          `attachment; filename="${topic}.pptx"`,
      },
    });
  } catch (error) {
    console.error(error);

    return Response.json(
      {
        error: "Failed generate ppt",
      },
      {
        status: 500,
      }
    );
  }
}